### PR TITLE
Risk rating content

### PR DESCRIPTION
**Pull request by adyhoran1**
Content tweaked to improve user experience.

### CODE REVIEW

**Review by mingoland — COMMENTED** [review]
All good to me - but how about the box in the "About the project" page? Is it okay to remain as "Risk rating and summary"?

**Comment by adyhoran1** [comment]
@mingoland let's keep it as that 👍🏻

**Comment by mingoland** [comment]
Alright then please just merge it

**Comment by adyhoran1** [comment]
Done 🙂

**Pull request merged**
